version: "3.7"

services:

  aftok:
    image: aftok/aftok-server:latest
    container_name: aftok-server
    expose:
      - "8000"
    depends_on:
      - aftokdb
      - zcashd
    volumes:
      - type: bind
        source: ./local/conf/server
        target: /etc/aftok
    networks:
      - front-tier
      - back-tier
    init: true
    entrypoint: "/etc/aftok/start_server.sh"
    command: ["aftok-db", "/opt/aftok/bin/aftok-server"]


  nginx:
    image: nginx:latest
    container_name: aftok-nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - aftok
    volumes:
      - type: bind
        source: ./local/conf/nginx/
        target: /etc/nginx
      - type: bind
        source: ./local/conf/nginx-certs
        target: /opt/nginx
      - type: bind
        source: ./aftok.com/dist/
        target: /opt/static/site
      - type: bind
        source: ./client/dist/
        target: /opt/static/app
      - type: bind
        source: ./reactclient/build
        target: /opt/static/app2
    networks:
      - front-tier

  aftokdb:
    image: postgres:9.4
    container_name: aftok-db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - type: volume
        source: aftok-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./local/db-dumps
        target: /opt/
    networks:
      - back-tier

  zcashd:
    image: electriccoinco/zcashd:v4.0.0
    container_name: aftok-zcashd
    expose:
      - "18232"
    ports:
      - "18232:18232"
    volumes:
      - type: bind
        source: ./local/conf/zcashd/zcash-data
        target: /srv/zcashd/.zcash
      - type: bind
        source: ./local/conf/zcashd/zcash-params
        target: /srv/zcashd/.zcash-params
    networks:
      - back-tier

volumes:
  aftok-data:

networks:
  front-tier:
  back-tier:
