version: "3.7"

services:
  aftok:
    image: aftok/aftok-server:latest
    container_name: aftok-server
    expose:
      - "8000"
    depends_on:
      - aftokdb
      - zcashd
    volumes:
      - type: bind
        source: ./local/server/conf
        target: /etc/aftok
        read_only: true
      - type: bind
        source: ./local/server/log
        target: /opt/aftok/log
    networks:
      - front-tier
      - back-tier
    init: true

  nginx:
    image: nginx:latest
    container_name: aftok-nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - aftok
    volumes:
      - type: bind
        source: ./local/nginx/conf
        target: /etc/nginx
        read_only: true
      - type: bind
        source: ./local/nginx/certs
        target: /opt/nginx
        read_only: true
      - type: bind
        source: ./local/nginx/log
        target: /var/log/nginx
      - type: bind
        source: ./aftok.com/dist
        target: /opt/static/site
        read_only: true
      - type: bind
        source: ./client/dist
        target: /opt/static/app
        read_only: true
      - type: bind
        source: ./reactclient/build
        target: /opt/static/app2
    networks:
      - front-tier

  aftokdb:
    image: postgres:9.4
    container_name: aftok-db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - type: volume
        source: aftok-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./local/postgres/db-dumps
        target: /opt/
        read_only: true
    networks:
      - back-tier

  zcashd:
    image: electriccoinco/zcashd:v4.0.0
    container_name: aftok-zcashd
    expose:
      - "18232"
    ports:
      - "18233:18233"
    volumes:
      - type: bind
        source: ./local/zcashd/zcash-data
        target: /srv/zcashd/.zcash
      - type: bind
        source: ./local/zcashd/zcash-params
        target: /srv/zcashd/.zcash-params
        read_only: true
    networks:
      - back-tier

volumes:
  aftok-data:

networks:
  front-tier:
  back-tier:
